version: '3'
services:
  db:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=newuser
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=tesing123
  web:
    build: .
    ports:
      - "9000:9000"
