version: '3'
services:
  db:
    image: mysql:5.7.32
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_USER=newuser
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=tesing123
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - ETHERSCAN_API_KEY=2WQZAX9F42ZFGXPBCKHXTTGYGU2A6CD6VG
      - DB_NAME=tesing123
      - DB_PASSWORD=password
      - DB_USERNAME=newuser
      - MYSQL_PORT=3306
      - MYSQL_HOST=db