apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
  local: {}
profiles:
- name: sandbox
  build:
    artifacts:
    - image: gcr.io/fetch-ai-sandbox/token-info-frontend
  deploy:
    kubectl:
      manifests:
        - "k8s/db/*.yaml"
        - "k8s/frontend/*.yaml"
        - "k8s/adminer/*.yaml"
        - "k8s/contractmon/*.yaml"
        - "k8s/istio.yaml"
  activation:
  - kubeContext: sandbox