---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: token-info
  namespace: token-info-page
spec:
  selector:
    app: istio-fetchpubig
    istio: ingressgateway
  servers:
  - hosts:
    - token-info.sandbox.fetch-ai.com
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - token-info.sandbox.fetch-ai.com
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: wildcard-sandbox
      mode: SIMPLE
      privateKey: sds
      serverCertificate: sds
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: token-info
  namespace: token-info-page
spec:
  gateways:
  - token-info
  hosts:
  - token-info.sandbox.fetch-ai.com
  http:
  - route:
    - destination:
        host: token-info-frontend.token-info-page.svc.cluster.local
        port:
          number: 80
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: token-info
  namespace: token-info-page
spec:
  endpoints:
  - dnsName:  token-info.sandbox.fetch-ai.com
    recordTTL: 180
    recordType: CNAME
    targets:
    - fetchpub.sandbox.fetch-ai.com/