apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
data:
  MYSQL_DATABASE: dG9rZW5pbmZv
  MYSQL_PASSWORD: SndpN1RxNExMZFhURmlabVJ3b2FOM2d6alR5N3BI
  MYSQL_ROOT_PASSWORD: aEE2cExwUERaNG9rTUp3aTdUcTRMTGRBNnBMcFBE
  MYSQL_USER: cm1aVEFpTTJWWXR2dFFoQTZwTHBQRFo0b2tNNHBD