apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appkey: token-info-web
  name: token-info-web
spec:
  replicas: 1
  selector:
    matchLabels:
      appkey: token-info-web
  template:
    metadata:
      labels:
        appkey: token-info-web
    spec:
      containers:
        - image: gcr.io/fetch-ai-sandbox/token-info-frontend:v0.2.6
          name: web
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: MYSQL_DATABASE

          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: MYSQL_USER

          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: MYSQL_PASSWORD
          
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: MYSQL_ROOT_PASSWORD

          - name: ETHERSCAN_API_KEY
            valueFrom:
            secretKeyRef:
              name: etherscan-api-key
              key: ETHERSCAN_API_KEY