name: Test build during PRs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Test docker image building
        run: |
          docker run -t test-build .