apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.18.0 ()
  labels:
    io.kompose.service: adminer
  name: adminer
  namespace: token-info-page
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: adminer
    spec:
      containers:
      - image: adminer:4.7
        name: adminer
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
